### ISSUE TITLE
Conductor-utilities adoption for oproduction usage

### ISSUE THREAD

**Issue by bimal10** [eugenechen0514/netflix-conductor-utilities#14]
Hey Eugene,

Wanted to know is it safe to use this package for creating workflows in production, Also Are you planning to add further contributions to this package in future as we see its not active for past 6 months.

Our use case: create workflows and task and taskdefs using typescript  for easy management of workflows

Please mention if any limitation exist of this library

**Comment by eugenechen0514** [comment]
Hi @bimal10 

There are some differences between conductor v2 and v3.The project basically is created for v2, and I still use it in production.

You may try https://github.com/conductor-sdk/conductor-javascript if you are using conductor v3.
