### ISSUE TITLE
Depreciation bug?

### ISSUE THREAD

**Issue by Germs31** [eugenechen0514/netflix-conductor-utilities#8]
Not sure if its a bug but it totally feels like a bug. Maybe i am not understanding this package very well. 

This line seems to produce some issues. it has also been noted that the endpoint is deprecated and once I comment out this line eveything works smoothly. 

```yield this.client.post(`${this.apiPath}/tasks/${taskId}/ack?workerid=${this.workerid}`);```

In ConductorWorker.ts, Line 87

**Comment by eugenechen0514** [comment]
Thank you @Germs31 

You are right.

I add `needAckTask` option (default false) in **ConductorWorker** to control whether a worker acknowledges a Conductor Server.
